namespace: flux-system
resources:
  - namespace.yaml
  - rbac.yaml
  - psp.yaml
bases:
  - ../../base/flux/
  - ../../base/memcached/
  - ../../base/helm-operator
patchesStrategicMerge:
  - flux-patch.yaml
