namespace: flagger-system
commonLabels:
  app: flagger
resources:
  - account.yaml
  - rbac.yaml
  - crd.yaml
  - deployment.yaml
namespace: linkerd
images:
  - name: weaveworks/flagger
    newTag: 0.21.0
