resources:
  - flux-helm-release-crd.yaml
  - flux-helm-operator-account.yaml
  - helm-operator-deployment.yaml
secretGenerator:
  - name: flux-helm-repositories
    files:
      - repositories.yaml
    type: Opaque