kind: HelmRelease
apiVersion: helm.fluxcd.io/v1
metadata:
  annotations:
    fluxcd.io/automated: "false"
  name: cert-manager
  namespace: certmanager
spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v0.1.0
