kind: Kustomization

bases:
  - ../../base/argocd/
  - ../../base/nginx-ingress/
  - ../../base/certmanager
  - ../../base/flagger

resources:
  - namespaces/infrastructure.yaml
  - namespaces/operations.yaml
  - namespaces/certmanager.yaml
  - namespaces/project1.yaml

patchesStrategicMerge:
  - linkerd-patch.yaml